---
- hosts: windows
  remote_user: root

  tasks:
  - name: Check for OS running services
    raw: |
      $OS_service_item = $null
      $OS_service_item += Get-WmiObject -Class Win32_Service -Filter {State = 'Stopped' and StartMode = 'Auto' } |
        where { $_.PathName -match "C:\\Windows\\System32*"  } |
      ForEach-Object {Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Services\$($_.Name)" |
        Where-Object {$_.Start -eq 2 -and $_.DelayedAutoStart -ne 1}} |
      Select-Object -Property @{expression={$_.PSChildName}} | ft -HideTableHeaders
      foreach ($item in $OS_service_item ) {
          Get-Service $item | Start-Service
    }
    register: OS_services

  - name: Set Facts for status tracking
    set_fact:
     RemediationStatus: Fixed
    ignore_errors: yes
    when:
    - OS_services.stdout_lines | length == 0
